/***************************************************************/
/*                                                             */
/* RSMIDI.H                                                    */
/*            COPYRIGHT (C) 1994 FUJITSU LIMITED               */
/*                                                             */
/***************************************************************/

#define	RSMTYPEA	0
#define	RSMTYPEB	1
#define	RSMTYPEC	2
extern	RSM_Init(int type,PORT port);
extern	RSM_Term();
